# Generated by Django 5.1.3 on 2024-12-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='flowers/photos')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.species')),
            ],
            options={
                'verbose_name': 'Gul ',
                'verbose_name_plural': 'Gullar',
            },
        ),
    ]
