# Generated by Django 5.1.3 on 2024-12-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
