# Generated by Django 5.1.3 on 2024-12-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flowers_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'ordering': ('created_at',), 'verbose_name': 'Gul ', 'verbose_name_plural': 'Gullar'},
        ),
        migrations.AlterField(
            model_name='flowers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Galochka turgan holatda mavjud aks holda esa mavjud emas!', verbose_name='Mavjud yoki Yoq'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Gul nomi'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.species', verbose_name='Tur nomi'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tur nomi'),
        ),
    ]
